language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
  - secure: u2LMDDpqiB3r9bvEiUL7jcIfZrubL428Q07W0g4hrMU2onATtgCIkT0DUlc/271sGujqrNogLocQ7fhxNRP4apATlUzUaKbpjz8tlJ5ebFdx1F0iu9ZQSu8qtXUigraHSgmqKtK3QDFf63QRbIyAJJFk1phfchzncDqRTEjGl6uKeBD5ns0se/NlMJeioKIuIeT1tlMp3nHSHVfODmJLcRevMp9WRm5T03hQDkmVdFzlMHp/t7GvqOIUM2xG/yx7bsMHcCE/f4eNxA6PnR9IzMEShaXewFHOgE3Xo+9SZt7Dt3NwFwc1hM2CBiv9QrVmRhsupgc+TD10DtcHz9r5fKXlsP9L5Do8850kTx4UzwKpRIYlYl+jrA/tMgT9gQZGVYaSh/zM26VyPYZq7rz114k8v0pE5TEUzR+XR1ZkZNxz/XFYzLohpXN0uct09nYwJl0pW/6BIll7ekd9H8C9R1qRADKMqkGTOmPYEdysVIcFG0Xa7cqK0Pu1szQ2duTFro+xqtDevWNM0Am6Ae0TiOXikob2rUr3w0Nu9dQ8D7T3nHAOs8p9Z5gpKJweV/zc2+yujR6UroxB+xEcxKWdfRYuj7wYo9QjVOUOCtaynS8WQUKAUCmELd8Jkb4/Z97ko3NrlaDsQWIp/PsJcnTlFqYbQEGGP54SFhX0uIZoa4g=
  - secure: s9lAOElraL/XkQ8kXBJgB2Abwhy8oWK/N82xTQkddFdEuRdS00y2r+Pd5ohbXRu+d8ilMSEGfTOMfCnJYGJLXwm3SHHYKNQrqP3ku7co88MygLrfEKHKBeCyqam3Gi3McJjTwTh1B1R6CheZGjn9o4DnE+oLGbOPghpFD0A49awuXthEOyzsBSMzMObuWlgq4DIVCQwPJijRgnYVdBNHYY3Tt+BWJjC21wX0MvWMJ0Wx4E/+x7fSCdn0Hx4nv+0ScpXxF2T2k5jWsZrfK/9ki8SwCpbr49MiGsKL/ouLHHSZtI679dvvqQbrqfmVsZiCTW4o/3WXRNJUT8N6WbHINh/2w5QYCrMIDQg0JDbNX1G5fiLDmgHRzuj5gR1/JB97Y5StMjzVwA7XF6a6qaqdVfbTOLvHhfp8+99wLG/Y2GnyfYStYJKhhvJ2g2Qr9Fe6hfgobuMAWHnkI/aH4yekEXoa05NRLWVjp+vD4Aa0Wujpo/Lw1NoNSFL8p0MvgRPAXLu1AqXBmFrSHfmpigE7K51HgsgfKolYyzf4RfPJB10P/mTwH0tWYvOTD/OtDmCjS+vXaoh9P8gUWNiIA56DmDcWodG/GTq7HsBuG1cSqhSVo1M5KPzCLukty73YmoqxnHEjwOYTjaMu/r1lPVeul+pKw07fK7JfGWXvmmo3XXE=
